In [1]:
import numpy as np

In [4]:
x=np.array(10)
print(x)
print(type(x))
print(x.ndim)

10
<class 'numpy.ndarray'>
0


# 1_D

In [15]:
l=[1,2,3,4,5,6]
x1=np.array(l)
print(x1)
print(x1.ndim)
x1.shape

[1 2 3 4 5 6]
1


(6,)

# 2_D

In [20]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
x2=np.array(l1)
print(x2)
print(x2.ndim)
print(x2[0:,::-2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[3 1]
 [6 4]
 [9 7]]


In [12]:
x2.shape[0]

3

# 3_D

In [13]:
l1=[[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]]
x3=np.array(l1)
print(x3)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [19]:
x3.shape

(2, 3, 3)

In [21]:
x3[1,1,-1]

16

In [22]:
x=np.arange(1,101)
z=np.array(x)
print(z)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [24]:
z.reshape(5,4,5)

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [26]:
x=np.arange(1,11)
x1=np.array(x)
print(x1)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
x3=np.array_split(x1,5)
print(x3)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


In [32]:
x3=np.array_split(x1,11)
print(x3)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9]), array([10]), array([], dtype=int32)]


In [36]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(l1)
print(a)
print("*"*50)
l2=[[11,12,13],[14,15,16],[17,18,19]]
b=np.array(l2)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**************************************************
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [41]:
q=np.concatenate((a,b),axis=1)
print(q)
q.shape

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


(3, 6)

In [42]:
x=np.arange(1,11)
x1=np.array(x)
print(x1)

[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
np.where(x1%2==0)

(array([1, 3, 5, 7, 9], dtype=int64),)

In [44]:
l=[11,18,9,0,12,14,6,7,8,21,35,67,7,7]
x1=np.array(l)
print(x1)

[11 18  9  0 12 14  6  7  8 21 35 67  7  7]


In [45]:
np.where(x1>15)

(array([ 1,  9, 10, 11], dtype=int64),)

In [47]:
print(q)

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [50]:
np.where(q>15,"A",(np.where(q>10,"B","C")))

array([['C', 'C', 'C', 'B', 'B', 'B'],
       ['C', 'C', 'C', 'B', 'B', 'A'],
       ['C', 'C', 'C', 'A', 'A', 'A']], dtype='<U1')

In [55]:
l1=[[11,2,13],[41,15,61],[17,16,19]]
x2=np.array(l1)
print(x2)


[[11  2 13]
 [41 15 61]
 [17 16 19]]


In [52]:
np.sort(x2)

array([[ 2, 11, 13],
       [15, 41, 61],
       [ 8, 17, 19]])

In [56]:
np.sort(x2,axis=0)

array([[11,  2, 13],
       [17, 15, 19],
       [41, 16, 61]])

In [58]:
for i in np.nditer(x2):
    print(i)

11
2
13
41
15
61
17
16
19


In [59]:
x=np.arange(100,200,10)
y=np.array(x).reshape(5,2)
print(y)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
